# Spring Boot 配置文件
server:
  port: 8080                    # 服务器端口
  servlet:
    context-path: /             # 应用根路径

spring:
  application:
    name: user-manager          # 应用名称
  
  # 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/user_manager?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: app_user
    password: app123
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 连接池配置
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  # JPA 配置
  jpa:
    hibernate:
      ddl-auto: update          # 开发环境使用update，生产环境使用validate
    show-sql: true              # 显示SQL语句
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  
  # Redis 配置
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 5000ms
      jedis:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 2
          max-wait: 2000ms
  
  # RabbitMQ 配置
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 5
        max-concurrency: 10
  
  # Thymeleaf模板配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false                # 开发环境关闭缓存
    encoding: UTF-8
    
  # 开发工具配置
  devtools:
    restart:
      enabled: true             # 启用热重载

# 日志配置
logging:
  level:
    com.example.usermanager: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info 